name: Go CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go 1.21
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Build
      run: go build

